naam = input("Voer jouw naam in : ")
adres = input("Voer jouw adres in : ")
postcode = input("Voer jouw postcode in : ")
woonplaats = input("Voer jouw woonplaats in : ")

print("- - - - - - - - - - - - - - - - - - - ")
print(f"|Naam : {naam} ")
print(f"|Adres : {adres} ")
print(f"|Postcode : {postcode} ")
print(f"|Woonplaats : {woonplaats} ")
print("- - - - - - - - - - - - - - - - - - - ")